Add associations
Ngufor-emmanuella/opp-school-libery pull request #3
Opened 2023-01-18 11:38 UTC by Ngufor-emmanuella

### In this milestone of the project I added the following classes ;

1. Created a class Classroom
2. Created the has-many/belongs-to relationship between Classroom and Student
3. Created a class Book
4. Created a class Rental
5. Create the many-to-many relationship between Person and Book using the intermediate class Rental

2023-01-18 11:50 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @Ngufor-emmanuella,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-18 11:50 UTC, Omar-Muhamad commented on books.rb
> +
- [ ] Please add Getters and Setters (attr_accessor) for `@rentals`, not Getters only (attr_reader) as you did.

2023-01-18 11:50 UTC, Omar-Muhamad commented on books.rb
> +  end
- [ ] This method suppose to create rentals and the book itself should be sent as a parameter to create the new rental achieving the 'has-many' association, So please fix that.
[Hint] the method will be like that:
```ruby
def add_rental(person, date) 
    Rental.new(date, self, person)
end
```

2023-01-18 11:50 UTC, Omar-Muhamad commented on person.rb
- [ ] Same here, Please add Getters and Setters (attr_accessor) for `@rentals`, not Getters only (attr_reader) as you did.

2023-01-18 11:50 UTC, Omar-Muhamad commented on person.rb
> +  end
- [ ] Same here,  This method suppose to create rentals and the book itself should be sent as a parameter to create the new rental achieving the 'has-many' association, So please fix that.

2023-01-19 11:39 UTC, m05e5 approved these changes
**Hi @Ngufor-emmanuella 

You did great. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![CleverScornfulBuffalo-size_restricted](https://user-images.githubusercontent.com/37901469/208869296-5ca9f6cc-a1b5-48fd-bd59-78fd83b35471.gif)

## Highlights
✔️ Descriptive PR 
✔️ your linters are all ok

## Optional suggestions


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**

2023-01-20 00:52 UTC, merged